Repository nhs-r-community/NHSRdatasets, pull requests merged in 2024-10, with the labels that each got.

#87 Add getting started
  R/LOS_model.R
  R/ae_attendances.R
  R/covid19.R
  R/ons_mortality.R
  R/stranded_patient_model.R
  R/synthetic_news_data.R
  README.Rmd
  README.md
  data-raw/ons-mortality.R
  man/LOS_model.Rd
  man/ae_attendances.Rd
  man/covid19.Rd
  man/ons_mortality.Rd
  man/stranded_data.Rd
  man/synthetic_news_data.Rd
  vignettes/NHSRdatasets.Rmd
Labels: documentation

#96 Added .all-contributorsrc to .Rbuildignore
  .Rbuildignore
Labels: bug

#88 Update synthetic_news_data.Rmd
  vignettes/synthetic_news_data.Rmd
Labels: Add vignette
